### PR TITLE
Consider scroll_context_lines setting for H and L

### PR DESCRIPTION
**Pull request by frithrah**
Avoids scrolling the view when using H or L with scroll_context_lines set.

### CODE REVIEW

**Comment by frithrah** [comment]
Hold on. I need to adjust the extent check too.

**Comment by gerardroche** [comment]
Very good.  Can you use `get_option(view, 'scrolloff')` instead of `view.settings().get('scroll_context_lines')`

The `scrolloff` option essentially proxies to `scroll_context_lines` so you can do things like `:set scrolloff=8`.

Some tests will need to be tweaked. I'll take a look at that now and see if the effected tests can just set the scrolloff option 0 for the existing tests and maybe one or two additional tests testing the scrollofff option set to higher value to test the context.

**Comment by gerardroche** [comment]
I made the H and L tests less flaky (https://github.com/NeoVintageous/NeoVintageous/commit/b7ede7b387c01b25697f879c86299bdb789a3577), so you can rebase and the tests for the PR should now pass.

**Comment by frithrah** [comment]
Thank you Gerard. I didn't notice the tests - apologies. I'll make those changes now.

**Comment by gerardroche** [comment]
When you rebase the tests should pass now. There's no need to write additional tests, those particular tests kinda complicated because they require mocking the ui.

**Comment by gerardroche** [comment]
You can add these tests if you like:

> `tests/functional/test__big_l.py`

```
    @unittest.mock_ui()
    def test_n_with_scrolloff(self):
        self.set_option('scrolloff', 2)
        self.eq('1\n2\n3\n4\n|5\n6\n7\n8\n', 'n_L', '1\n2\n3\n4\n5\n|6\n7\n8\n')
```

> `tests/functional/test__big_h.py`

```
    @unittest.mock_ui()
    def test_n_with_scrolloff(self):
        self.set_option('scrolloff', 2)
        self.eq('1\n2\n3\n4\n|5\n6\n7\n8\n', 'n_H', '1\n2\n|3\n4\n5\n6\n7\n8\n')
```

**Comment by frithrah** [comment]
Thank you Gerard. I'm grateful for your devotion to making Sublime so Vim-compatible.

**Pull request closed without merging**
