### PR TITLE
Support non-QWERTY non-Latin layouts and I18n multisym

### PR DESCRIPTION
**Pull request by eugenesvk**
This PR adds two great new features to NeoVintageous:
1. it allows you to generate a __non-QWERTY layout__ (including non-Latin) (basically automatically generates a native Sublime Text keymap replacing only the keycaps, which previously needed to be done manually, which is practically impossible for a huge set of keybindings that NV has)
a user needs to add to his config (changed it to a dictionary to avoid those huge config key names)
```jsonc
"neo_vintageous"  	: {
  "keymap"        	: { //the order should match the QWERTY layout, spaces are ignored
    "lower"       	:    "ё12 34567890-=\\ йцукенгшщзхъ фывапролджэ ячсмитьбю.",
    //'qwerty_low'	: R'''`12 34567890-=\  qwertyuiop[] asdfghjkl;' zxcvbnm,./'''
    "upper"       	:    "Ё!\"№;%:?*()_+/  ЙЦУКЕНГШЩЗХЪ ФЫВАПРОЛДЖЭ ЯЧСМИТЬБЮ,",
    //'qwerty_upp'	: R'''~! @#$%^&*()_+|  QWERTYUIOP{} ASDFGHJKL:" ZXCVBNM<>?'''},
  },
},   
```
and then invoke a `NeoVintageous: Generate non-QWERTY keymap` command, and he'll get a `User/NeoVintageous/Default.sublime-keymap` that replicates the default keymap with the new layout (I've left the unchanged commands as is just in case, also helps comparing the files)
The generated config also looks identical to the default due to the nice `json5kit` library that can round-trip comments and all the whitespace!

The __downside__ is that this new file overrides `User/Default.sublime-keymap`, requiring moving it to a subfolder (there is a popup message on conversion explaining this)

2. it allows you to use alternative key symbols in `.neovintageous` config, simultaneously!, e.g.,
```
noremap	<Right>   	j
noremap	<▶>       	k
noremap	<pagedown>	h
noremap	<⇟>       	l
```

by converting most keybinds from strings to lists and replacing command assignments from literal variables to sequence dictionary keys
```py
@register(seqs.LEFT_SQUARE_BRACKET_L, (NORMAL, VISUAL)) # from
@register(seqs.SEQ['[l']            , (NORMAL, VISUAL)) # to
```
It also autogenerates most of these keys from a list of keycaps and modifiers (or prefixes like `[`), so makes the whole system more extensible and cleaner vs. having to manually name all the variables

(by the way, the same principle of autogenerating key sequences could be used to autogenerate the default keymap as it's tedious to add keys manually and easy to forget some like https://github.com/NeoVintageous/NeoVintageous/pull/868)

This would also allow (tried for a few keys, but __not implemented__) a user to use non-latin keycaps in config! e.g., adding this to a keymap (later on this should be autogenerated like in part 1)
```json
{"keys": ["й"],         "command": "nv_feed_key", "args": {"key": "й"},        "context": [{"key": "vi_command_mode_aware"}]},
```
allows you to remap
`noremap й	 w`

so if you don't want to have the same physical keys mapped to the same functions in non-latin and latin layouts, you could do that!
(I thought this required adding something like `SEQ['q'] += ['й']` to sequence key list, but seems that maybe not, just adding keymaps seems to be sufficient)

(this includes a fix for invalid register error for non-latin macros, so <kbd>й</kbd><kbd>й</kbd><kbd>й</kbd> works just like <kbd>q</kbd><kbd>q</kbd><kbd>q</kbd> even when you have `й` mapped to `й`, not `q`)

Also includes a few minor tweaks here and there like making the command list more readable as a single vertically aligned table

Closes (already closed, but not fully resolved): https://github.com/NeoVintageous/NeoVintageous/issues/274
https://github.com/NeoVintageous/NeoVintageous/issues/61

### CODE REVIEW

**Comment by gerardroche** [comment]
I think this is too much of a change for me. If I understand correctly what it is you're trying to do, I think this would be better as a plugin by itself i.e. a key binding generator or not even specifically for NeoVintageous. I assume non-qwerty users who use NeoVintageous use other tools or manually copy the NeoVintageous key bindings and update all the necessary keys.

**Comment by eugenesvk** [comment]
> better as a plugin by itself i.e. a key binding generator or not even specifically for NeoVintageous

But then why do you have XkbSwitch in the Roadmap if you wanted this functionality to be outside of NV? This approach is superior as it doesn't mess with user's layouts
https://github.com/NeoVintageous/NeoVintageous/issues/855
https://github.com/NeoVintageous/NeoVintageous/issues/276

Also note that this generator could be extended for the main keymap as well to avoid missing keys and making it easier to change/extend.

> I assume non-qwerty users who use NeoVintageous use other tools or manually copy the NeoVintageous key bindings and update all the necessary keys.

Sure, or they mostly become not-NVin(m) users :) as requiring other tools or manually copying&modifying a (subset) of hundreds of keybinds is a big usability barrier, I mean, lack of int support is one of the rather more common persistent issue with such apps

**Comment by gerardroche** [comment]
This isn't something that I'm going to merge. It changes too many things that I'm not comfortable with. I don't want to be unclear about that because the last thing I want is to mislead you into thinking that it is on the right path so investing more time will get it done only for me to still reject it.

If this is still something you want to pursue I would suggest trying to implement it as a separate i18n/non-qwerty keymap generator plugin. And maybe it's time for me to try devorak or colemak.

**Comment by eugenesvk** [comment]
Autogeneration is only one part of the i18n story, the other part that you didn't address is for the plugin to actually generate command bindings so that those other keys (and key symbols) can be used in user config (all the command `assign` etc bindings need to be adjusted within the plugin), thus don't think it's feasible to separate it.

**Pull request closed without merging**
