### PR TITLE
Run user cli commands on mode change

### LINKED ISSUE #932: Run a cli command on every mode change
I'd like to add a typo-free And convenient way to exit Insert mode.
One such way is to bind hold <kbd>i</kbd> to <kbd>⎋</kbd>, but Sublime/NV can't handle taps vs hold keys.
Other key remapping apps can, but then they don't know what mode NV is currently in, so they can't remap <kbd>i</kbd> only in Insert mode
But NV could send those apps a `cli` signal on every mode switch (would differ depending on the source/target mode)

So would it be possible to add some kind of optional hook that would execute a cli command on every mode switch? Then I could se this command to, eg, send to Karabiner Elements on a Mac a command to set `isNVⓘ` whenever NV enters Insert mode, and then within Karabiner Elements I'd set up <kbd>i</kbd> on hold to exit, but otherwise continue to type `i`

### PR DESCRIPTION
**Pull request by eugenesvk**
By setting something like this in `NeoVintageous.sublime-settings` (a separate file allows using shorter names and subscribing to plugin-specific file changes)
```json5
{
"events"       	: {
  "osx"        	: {
  "InsertEnter"	: ["~/.local/bin/karabiner_cli", "--set-variables", "{\"isNVⓘ\":1}"],
  "InsertLeave"	: ["~/.local/bin/karabiner_cli", "--set-variables", "{\"isNVⓘ\":0}"],
  "NormalEnter"	: ["~/.local/bin/karabiner_cli", "--set-variables", "{\"isNVⓃ\":1}"],
  "NormalLeave"	: ["~/.local/bin/karabiner_cli", "--set-variables", "{\"isNVⓃ\":0}"],
  },
}
}
```

closes #932

### CODE REVIEW

**Review by gerardroche — CHANGES_REQUESTED** [review]
Make sure CI is passing. I make the contributing doc a little better. 

https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md

Neo supports for ST3 and ST4. ST3 (build 3211) uses Python 3.3.6.

For instance, f-strings are not compatible in ST3.

**Comment by eugenesvk** [comment]
I'll uglify the coding style after other issues are resolved

**Comment by eugenesvk** [comment]
> Neo supports for ST3 and ST4. ST3 (build 3211) uses Python 3.3.6.

Could you then add it to a tag for the ST4 version? If someone is still using the old version, they could remove the better syntax to match ST3

**Comment by gerardroche** [comment]
No. ST3 support won't be removed any time soon. I can't maintain multiple branches.

**Pull request closed without merging**
